name: my_weekplaner_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  firebase_analytics: ^10.7.4
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.8
  intl: ^0.18.1
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter_icons:
  android: true
  ios: true
  image_path: assets/icons/App-Icon.png

flutter:
  uses-material-design: true
  assets:
    - assets/