// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4GTk_rKvXmRbjTII2HIaFj3nbPUlQsnw',
    appId: '1:771165996875:web:a052a387ff430ee321cace',
    messagingSenderId: '771165996875',
    projectId: 'my-weekplaner',
    authDomain: 'my-weekplaner.firebaseapp.com',
    storageBucket: 'my-weekplaner.appspot.com',
    measurementId: 'G-XHD62YTDGE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwER1rgOkS06bqgKCGu7tIX5x7FmXDCFM',
    appId: '1:771165996875:android:25a907098e5d601f21cace',
    messagingSenderId: '771165996875',
    projectId: 'my-weekplaner',
    storageBucket: 'my-weekplaner.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo0gsKVIAl0w8L6bcT9LQsg6Njjx3IsiM',
    appId: '1:771165996875:ios:57002d36cd92789721cace',
    messagingSenderId: '771165996875',
    projectId: 'my-weekplaner',
    storageBucket: 'my-weekplaner.appspot.com',
    iosBundleId: 'com.example.myWeekplanerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo0gsKVIAl0w8L6bcT9LQsg6Njjx3IsiM',
    appId: '1:771165996875:ios:83dc0aa78e23a03021cace',
    messagingSenderId: '771165996875',
    projectId: 'my-weekplaner',
    storageBucket: 'my-weekplaner.appspot.com',
    iosBundleId: 'com.example.myWeekplanerApp.RunnerTests',
  );
}
